name: Varbase Blog Base
description: A recipe to provide a blog post content type, listing page, and related configuration for Varbase. Use Blog to publish blog posts by different authors in the Blog section of the site.
type: Varbase Blog
recipes:
  - varbase_content_base
  - varbase_media_base
  - varbase_seo_base
  - varbase_workflow_base
install:
  - selective_better_exposed_filters
config:
  strict: false
  actions:
    user.role.anonymous:
      grantPermissions:
        - 'access_unpublished node blog'
        - 'access_unpublished taxonomy_term blog_categories'
        - 'access_unpublished taxonomy_term tags'
    user.role.authenticated:
      grantPermissions:
        - 'access_unpublished node blog'
        - 'access_unpublished taxonomy_term blog_categories'
        - 'access_unpublished taxonomy_term tags'
    user.role.content_editor:
      grantPermissions:
        - 'create blog content'
        - 'create terms in blog_categories'
        - 'delete any blog content'
        - 'delete blog revisions'
        - 'delete own blog content'
        - 'edit any blog content'
        - 'edit own blog content'
        - 'reorder terms in blog_categories'
        - 'revert blog revisions'
        - 'select terms in blog_categories'
        - 'select unpublished terms in blog_categories'
        - 'view blog revisions'
        - 'view term names in blog_categories'
        - 'view terms in blog_categories'
        - 'view unpublished term names in blog_categories'
        - 'view unpublished terms in blog_categories'
        - 'view vocabulary name of blog_categories'
    user.role.content_admin:
      grantPermissions:
        - 'create blog content'
        - 'create terms in blog_categories'
        - 'delete any blog content'
        - 'delete blog revisions'
        - 'delete own blog content'
        - 'delete terms in blog_categories'
        - 'edit any blog content'
        - 'edit own blog content'
        - 'edit terms in blog_categories'
        - 'reorder terms in blog_categories'
        - 'revert blog revisions'
        - 'select terms in blog_categories'
        - 'select unpublished terms in blog_categories'
        - 'view blog revisions'
        - 'view term names in blog_categories'
        - 'view terms in blog_categories'
        - 'view unpublished term names in blog_categories'
        - 'view unpublished terms in blog_categories'
        - 'view vocabulary name of blog_categories'
    user.role.seo_admin:
      grantPermissions:
        - 'create blog content'
        - 'create terms in blog_categories'
        - 'delete any blog content'
        - 'delete own blog content'
        - 'edit any blog content'
        - 'edit own blog content'
        - 'reorder terms in blog_categories'
        - 'select terms in blog_categories'
        - 'select unpublished terms in blog_categories'
        - 'view blog revisions'
        - 'view term names in blog_categories'
        - 'view terms in blog_categories'
        - 'view unpublished term names in blog_categories'
        - 'view unpublished terms in blog_categories'
        - 'view vocabulary name of blog_categories'
    user.role.site_admin:
      grantPermissions:
        - 'create blog content'
        - 'create terms in blog_categories'
        - 'delete any blog content'
        - 'delete blog revisions'
        - 'delete own blog content'
        - 'delete terms in blog_categories'
        - 'edit any blog content'
        - 'edit own blog content'
        - 'edit terms in blog_categories'
        - 'reorder terms in blog_categories'
        - 'reset blog_categories'
        - 'revert blog revisions'
        - 'select terms in blog_categories'
        - 'select unpublished terms in blog_categories'
        - 'taxonomy manager export csv for blog_categories'
        - 'taxonomy manager export list for blog_categories'
        - 'view blog revisions'
        - 'view term names in blog_categories'
        - 'view terms in blog_categories'
        - 'view unpublished term names in blog_categories'
        - 'view unpublished terms in blog_categories'
        - 'view vocabulary name of blog_categories'
    workflows.workflow.varbase_editorial_workflow:
      addNodeTypes: ['blog']
